site_name: openshift-tigerteam
site_url: https://openshift-tigerteam.github.io

nav:
  - Home: 'index.md'
  - Installation Examples:
    - Assisted Installer: 'install/assisted/assisted-installer.md'
    - Day 2: 'install/day-2.md'
    - Multipath: 'install/multipath.md'
  - Deployment Examples:
    - BusyBox: 'busybox.md'
    - Quarkus: 'quarkus-demo.md'
  - Tools: 'pages/tools.md'

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/openshift-logo.png
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    - navigation.instant
    - navigation.sections


